CREATE TABLE CAD_PRODUTOS(
    ID BIGINT,
    NOME VARCHAR(255),
    EMISSOR VARCHAR(255),
    DATA_EMISSAO TIMESTAMP,
    AREA_UTILIZAÇAO VARCHAR (255),
    PRIMARY KEY(ID)
);
    CREATE SEQUENCE SEQ_CAD_PRODUTO AS BIGINT MINVALUE 1 START WITH 1 INCREMENT BY 1;
    


